package com.fa.beatify.ui.theme

import androidx.compose.ui.graphics.Color

val Transparent: Color = Color(color = 0x00000000)
val White: Color = Color(color = 0xFFFFFFFF)

val LtPrimary: Color = Color(color = 0xFFE94057)
val LtSelectionHandle: Color = Color(color = 0xFFE94057)
val LtSelectionBg: Color = Color(color = 0xFFFF8D9D)
val LtSysBars: Color = Color(color = 0xFFECECEC)
val LtScreenBg: Color = Color(0xFFECECEC)
val LtNavBarIndicator: Color = Color(color = 0xFFE94057)
val LtNavBarUnSelected: Color = Color(color = 0xFF696969)
val LtNavBarSelected: Color = Color(color = 0xFF414141)
val LtTextColor: Color = Color(color = 0xFF4D4D4D)
val LtSearchContainer: Color = Color(color = 0xFFCFCFCF)
val LtGridCategoryBg: Color = Color(0xFFECECEC)
val LtGridArtistBg: Color = Color(0xFFEBEBEB)
val LtNavIcon: Color = Color(0xFF696969)
val LtNavIconFill: Color = Color(0xFFFFFFFF)
val LtIcon: Color = Color(color = 0xFF414141)

val NtPrimary: Color = Color(color = 0xFFE94057)
val NtSelectionHandle: Color = Color(color = 0xFFE94057)
val NtSelectionBg: Color = Color(color = 0xFFFF8D9D)
val NtSysBars: Color = Color(color = 0xFF414141)
val NtScreenBg: Color = Color(0xFF202020)
val NtNavBarIndicator: Color = Color(color = 0xFFE94057)
val NtNavBarUnSelected: Color = Color(color = 0xFFB4B4B4)
val NtNavBarSelected: Color = Color(color = 0xFFE7E7E7)
val NtTextColor: Color = Color(color = 0xFFFFFFFF)
val NtSearchContainer: Color = Color(color = 0xFFCFCFCF)
val NtGridCategoryBg: Color = Color(0xBF202020)
val NtGridArtistBg: Color = Color(0xFF414141)
val NtNavIcon: Color = Color(0xFFFFFFFF)
val NtNavIconFill: Color = Color(0xFFFFFFFF)
val NtIcon: Color = Color(color = 0xFFFFFFFF)

val GridStrokeColor: Color = Color(color = 0xFFFF8D9D)
val GridStrokeColor2: Color = Color(color = 0xFFFD4A63)
val GridStrokeColor3: Color = Color(color = 0xFFFF0023)